---
- name: make sure man directory exist
  file:
    path: /usr/share/man/man1
    state: directory
- name: install openjdk
  apt:
    name: "openjdk-{{ jdk_major_version }}-jdk-headless"
    state: present
    update_cache: yes
