---
- name: Execute command to get destibutor on Hosts
  shell: 'lsb_release -i -s | tr "[A-Z]" "[a-z]"'
  args:
    executable: /bin/bash
  register: distributor

- name: Execute command to get code_name on Hosts
  shell: 'lsb_release -s -c'
  register: code_name
  args:
    executable: /bin/bash

- name: installa docker dependency
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: add GPG key
  apt_key:
    url: "https://download.docker.com/linux/{{distributor.stdout}}/gpg"
    state: present

- name: add docker repository to apt
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{distributor.stdout}} {{code_name.stdout}} stable"
    state: present

- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Download docker-compose {{ docker_compose_version }}
  get_url:
    url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: ~/docker-compose
    mode: '+x'

- name: Check docker-compose exists
  stat: path=~/docker-compose
  register: docker_compose

- name: Move docker-compose to /usr/local/bin/docker-compose
  command: mv ~/docker-compose /usr/local/bin/docker-compose
  when: docker_compose.stat.exists